### ISSUE TITLE
HTTP error 403

### ISSUE THREAD

**Issue by jmrchelani** [Techistan/md2urdu#18]
HTTPError: Response code 403 (Forbidden)
Url: https://translate.google.com/translate_a/single?client=t&sl=auto&tl=ur&hl=ur&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=---%0D%0Atitle%3A%20%22Client%20Commands%22%0D%0Adescripion%3A%20List%20of%20all%20client%20commands.%0D%0A---%0D%0A%0D%0A%7C%20Command%20%20%20%20%20%20%20%20%7C%20Description%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20--------------%20%7C%20--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------%20%7C%0D%0A%7C%20%2Fquit%20(%2Fq)%20%20%20%20%20%7C%20This%20command%20speaks%20for%20itself%2C%20it%20quits%20the%20game.%20You%20can%20also%20use%20%2Fq%2C%20as%20it%20the%20exact%20same%20command%2C%20just%20shorter.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Fsave%20%20%20%20%20%20%20%20%20%20%7C%20%2Fsave%20is%20most%20likely%20the%20most%20commonly%20used%20default%20command%2C%20and%20probably%20the%20most%20useful.%20When%20you%20type%20%2Fsave%2C%20your%20current%20position%20is%20saved%20to%20savedpositions.txt%20in%20your%20user%20files%20directory%2C%20from%20where%20you%20can%20use%20it%20in%20scripts.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Frs%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%2Frs%20(Raw%20Save)%20is%20like%20%2Fsave%2C%20but%20it%20only%20saves%20your%20current%20position%20and%20facing%20angle%20in%20rawpositions.txt%20in%20your%20user%20files%20directory.%20No%20extra%20information%20is%20saved%20such%20as%20class%20and%20weapons.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Finterior%20%20%20%20%20%20%7C%20Partly%20as%20important%20as%20%2Fsave%2C%20this%20command%20simply%20displays%20your%20current%20interior%20in%20chat.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Ffpslimit%20%20%20%20%20%20%7C%20This%20command%20sets%20the%20limit%20of%20FPS%20(Frames%20Per%20Second)%20for%20your%20game.%20The%20higher%20the%20limit%20the%20smoother%20your%20game%20is.%20Has%20no%20effect%20if%20frame%20limiter%20is%20turned%20off%20in%20graphic%20options.%20The%20limit%20can%20be%20set%20between%2020%20and%2090.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Fpagesize%20%20%20%20%20%20%7C%20%2Fpagesize%20is%20used%20to%20choose%20the%20amount%20of%20lines%20of%20chat%20to%20show.%20This%20can%20be%20anything%20from%2010%20to%2020%20lines.%20Pagesize%20is%2010%20by%20default.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Fheadmove%20%20%20%20%20%20%7C%20This%20command%20will%20enable%2Fdisable%20the%20players%20head%20movements%2C%20however%20it%20is%20handled%20locally%20so%20other%20players%20will%20still%20see%20your%20head%20move.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Ftimestamp%20%20%20%20%20%7C%20This%20command%20will%20show%2Fhide%20a%20time%20next%20to%20all%20messages%20in%20the%20chatbox.%20The%20time%20that%20is%20displayed%20is%20your%20computer's%20time%2C%20not%20the%20server%20time.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Fdl%20%20%20%20%20%20%20%20%20%20%20%20%7C%20DL%20stands%20for%20debug%20labels.%20This%20command%20toggles%20debug%20labels%20on%20vehicles%2C%20which%20show%20the%20vehicle%20ID%2C%20model%2C%20health%2C%20whether%20the%20vehicle%20is%20pre-loaded%2C%20distance%20from%20the%20player%2C%20trailer%2C%20available%20seats%2C%20current%20position%20and%20spawn%20position.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Fnametagstatus%20%7C%20This%20command%20was%20added%20in%200.3x.%20When%20enabled%20(which%20it%20is%20by%20default)%2C%20players%20will%20see%20a%20small%20hourglass%20icon%20next%20to%20the%20nametag%20of%20paused%20players.%20This%20includes%20minimising%20(alt-tab)%2C%20the%20pause%20menu%20(ESC)%2C%20lost%20connection%20(crash%2Ftimeout)%20and%20when%20taking%20screenshots%20that%20freeze%20the%20game%20for%20over%203%20seconds.%20%7C%0D%0A%7C%20%2Fmem%20%20%20%20%20%20%20%20%20%20%20%7C%20Shows%20the%20current%20amount%20of%20memory%20usage.%20(Although%2C%20it%20usually%20only%20prints%20128%20MB.)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Faudiomsg%20%20%20%20%20%20%7C%20Enables%2FDisables%20the%20message%20that%20prints%20when%20a%20url%20is%20streamed%20to%20a%20client.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Ffontsize%20%20%20%20%20%20%7C%20Changes%20the%20font%20size%20of%20the%20UI%20(chat%2C%20dialogs%20etc.).%20Valid%20fontsize%20is%20-3%20to%205.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Fctd%20%20%20%20%20%20%20%20%20%20%20%7C%20This%20command%20was%20added%20in%20SA-MP%200.3.7%20RC2.%20It%20enables%20client%20debugging%20of%20the%20player%20camera%20target.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A%7C%20%2Frcon%20%20%20%20%20%20%20%20%20%20%7C%20More%20related%20to%20the%20server%20rather%20than%20the%20client.%20This%20command%20is%20used%20to%20execute%20RCON%20commands.%20RCON%20is%20the%20built-in%20admin%20system.%20RCON%20stands%20for%20%5BRemote%20Control%5D(..%2Fserver%2FControllingServer%23using-rcon).%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0D%0A&tk=426183.426183

**Comment by jmrchelani** [comment]
The API or the translator version is outdated most probably.

**Comment by jmrchelani** [comment]
However, removing the `translate_a/single` from `https://translate.google.com/translate_a/single?client=t&sl=auto&tl=ur&hl=ur&dt=at&.................` does work..

**Comment by jmrchelani** [comment]
After enough finding and research, following is the reason why its not working:
1. Outdated dependency (api)
2. Google translate has changed their system of translation
Now, https://github.com/vkedwardli/google-translate-api/tree/batchexecute This is a working dependency (update of that old api) and must be used. Also a lot of modules need to be updated.
Hope it is fixed soon.

**Comment by MrSlimCoder** [comment]
@jmrchelani Hello, Thank you for this issue, We will surely look into this and will fix and get back to you.

**Comment by MrSlimCoder** [comment]
Fixed #19
